name: Java CI with Maven

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'RunTests')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B verify

    - name: Display JaCoCo Report Content
      run: cat coverage/target/site/jacoco-aggregate/jacoco.xml

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage/target/site/jacoco-aggregate/jacoco.xml
        format: jacoco
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
